package bloodborne.system;

public enum TextAnalyzer {EXPLORATION, FIGHT, RUNE, DEATH, QUIT, QUIT_FROM_DEATH, START, DREAM_BACK, LEVEL_UP, MERCHANT, UPGRADE, YHARNAM_HEADSTONE, FRONTIER_HEADSTONE, UNSEEN_HEADSTONE}
